server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            #域名版回调凭据会出问题
            #http://http://www.lstmontreal.com:8081/login/oauth2/code/google
            client-id: 976006583195-0s753p4ml231i6ioooeghk3knaiu97ff.apps.googleusercontent.com
            client-secret: ZZWe7lWwRd_a94pFjwwT9fyz
